//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------
namespace BookReaderApp.Resources {
    using System;
    using System.Globalization;
    using System.Resources;
    using System.Reflection;

    internal class Strings {
        static ResourceManager resourceMan;
        static CultureInfo resourceCulture;

        internal Strings() { }

        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("BookReaderApp.Resources.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string AfterUploadHint {
            get {
                return ResourceManager.GetString("AfterUploadHint", resourceCulture);
            }
        }

        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }

        internal static string BookLabel {
            get {
                return ResourceManager.GetString("BookLabel", resourceCulture);
            }
        }

        internal static string BookLanguage_English {
            get {
                return ResourceManager.GetString("BookLanguage_English", resourceCulture);
            }
        }

        internal static string BookLanguage_None {
            get {
                return ResourceManager.GetString("BookLanguage_None", resourceCulture);
            }
        }

        internal static string BookLanguage_Russian {
            get {
                return ResourceManager.GetString("BookLanguage_Russian", resourceCulture);
            }
        }

        internal static string Upload_Progress_Format {
            get {
                return ResourceManager.GetString("Upload_Progress_Format", resourceCulture);
            }
        }

        internal static string Upload_Error_LanguageNotSelected {
            get {
                return ResourceManager.GetString("Upload_Error_LanguageNotSelected", resourceCulture);
            }
        }

        internal static string Translation_Progress_TargetOnly {
            get {
                return ResourceManager.GetString("Translation_Progress_TargetOnly", resourceCulture);
            }
        }

        internal static string Translation_Progress_WithTitleTarget {
            get {
                return ResourceManager.GetString("Translation_Progress_WithTitleTarget", resourceCulture);
            }
        }

        internal static string Translation_Progress_TitleOnly {
            get {
                return ResourceManager.GetString("Translation_Progress_TitleOnly", resourceCulture);
            }
        }

        internal static string BookReaction_Favorite {
            get {
                return ResourceManager.GetString("BookReaction_Favorite", resourceCulture);
            }
        }

        internal static string BookReaction_None {
            get {
                return ResourceManager.GetString("BookReaction_None", resourceCulture);
            }
        }

        internal static string BookReaction_Unrated {
            get {
                return ResourceManager.GetString("BookReaction_Unrated", resourceCulture);
            }
        }

        internal static string BookSort_DateNew {
            get {
                return ResourceManager.GetString("BookSort_DateNew", resourceCulture);
            }
        }

        internal static string BookSort_DateOld {
            get {
                return ResourceManager.GetString("BookSort_DateOld", resourceCulture);
            }
        }

        internal static string BookSort_SizeAsc {
            get {
                return ResourceManager.GetString("BookSort_SizeAsc", resourceCulture);
            }
        }

        internal static string BookSort_SizeDesc {
            get {
                return ResourceManager.GetString("BookSort_SizeDesc", resourceCulture);
            }
        }

        internal static string BookSort_TitleAsc {
            get {
                return ResourceManager.GetString("BookSort_TitleAsc", resourceCulture);
            }
        }

        internal static string BookSort_TitleDesc {
            get {
                return ResourceManager.GetString("BookSort_TitleDesc", resourceCulture);
            }
        }

        internal static string BookStatus_InProgress {
            get {
                return ResourceManager.GetString("BookStatus_InProgress", resourceCulture);
            }
        }

        internal static string BookStatus_New {
            get {
                return ResourceManager.GetString("BookStatus_New", resourceCulture);
            }
        }

        internal static string BookStatus_None {
            get {
                return ResourceManager.GetString("BookStatus_None", resourceCulture);
            }
        }

        internal static string BookStatus_Read {
            get {
                return ResourceManager.GetString("BookStatus_Read", resourceCulture);
            }
        }

        internal static string DateAddedLabel {
            get {
                return ResourceManager.GetString("DateAddedLabel", resourceCulture);
            }
        }

        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }

        internal static string GoTopLabel {
            get {
                return ResourceManager.GetString("GoTopLabel", resourceCulture);
            }
        }

        internal static string InterfaceFontSizeLabel {
            get {
                return ResourceManager.GetString("InterfaceFontSizeLabel", resourceCulture);
            }
        }

        internal static string InterfaceSettingsTitle {
            get {
                return ResourceManager.GetString("InterfaceSettingsTitle", resourceCulture);
            }
        }

        internal static string InterfaceThemeLabel {
            get {
                return ResourceManager.GetString("InterfaceThemeLabel", resourceCulture);
            }
        }

        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }

        internal static string LastOpenedLabel {
            get {
                return ResourceManager.GetString("LastOpenedLabel", resourceCulture);
            }
        }

        internal static string PagesLabel {
            get {
                return ResourceManager.GetString("PagesLabel", resourceCulture);
            }
        }

        internal static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }

        internal static string SearchButtonLabel {
            get {
                return ResourceManager.GetString("SearchButtonLabel", resourceCulture);
            }
        }

        internal static string Search_CollapseSearch {
            get {
                return ResourceManager.GetString("Search_CollapseSearch", resourceCulture);
            }
        }

        internal static string Notes_AddNoteSoonTitle {
            get {
                return ResourceManager.GetString("Notes_AddNoteSoonTitle", resourceCulture);
            }
        }

        internal static string Notes_AddNoteSoonBody {
            get {
                return ResourceManager.GetString("Notes_AddNoteSoonBody", resourceCulture);
            }
        }

        internal static string Notes_ScreenTitle {
            get {
                return ResourceManager.GetString("Notes_ScreenTitle", resourceCulture);
            }
        }

        internal static string Notes_MyNotes {
            get {
                return ResourceManager.GetString("Notes_MyNotes", resourceCulture);
            }
        }

        internal static string Notes_AddNote {
            get {
                return ResourceManager.GetString("Notes_AddNote", resourceCulture);
            }
        }

        internal static string Notes_PageFormat {
            get {
                return ResourceManager.GetString("Notes_PageFormat", resourceCulture);
            }
        }

        internal static string Notes_Untitled {
            get {
                return ResourceManager.GetString("Notes_Untitled", resourceCulture);
            }
        }

        internal static string Notes_EditorTitle {
            get {
                return ResourceManager.GetString("Notes_EditorTitle", resourceCulture);
            }
        }

        internal static string Notes_TitleField {
            get {
                return ResourceManager.GetString("Notes_TitleField", resourceCulture);
            }
        }
        
        internal static string Notes_TitlePlaceholder {
            get {
                return ResourceManager.GetString("Notes_TitlePlaceholder", resourceCulture);
            }
        }
        
        internal static string Notes_TitleRequiredTitle {
            get {
                return ResourceManager.GetString("Notes_TitleRequiredTitle", resourceCulture);
            }
        }
        
        internal static string Notes_TitleRequiredMessage {
            get {
                return ResourceManager.GetString("Notes_TitleRequiredMessage", resourceCulture);
            }
        }

        internal static string Notes_CommentPlaceholder {
            get {
                return ResourceManager.GetString("Notes_CommentPlaceholder", resourceCulture);
            }
        }

        internal static string Notes_Save {
            get {
                return ResourceManager.GetString("Notes_Save", resourceCulture);
            }
        }

        internal static string Notes_VersionUnavailable {
            get {
                return ResourceManager.GetString("Notes_VersionUnavailable", resourceCulture);
            }
        }

        internal static string Notes_NoNotesYet {
            get {
                return ResourceManager.GetString("Notes_NoNotesYet", resourceCulture);
            }
        }

        internal static string Notes_SavedSuccess {
            get {
                return ResourceManager.GetString("Notes_SavedSuccess", resourceCulture);
            }
        }

        internal static string Notes_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("Notes_DeleteConfirmTitle", resourceCulture);
            }
        }

        internal static string Notes_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("Notes_DeleteConfirmMessage", resourceCulture);
            }
        }

        internal static string Notes_DeleteConfirmAction {
            get {
                return ResourceManager.GetString("Notes_DeleteConfirmAction", resourceCulture);
            }
        }

        internal static string Notes_DeletedSuccess {
            get {
                return ResourceManager.GetString("Notes_DeletedSuccess", resourceCulture);
            }
        }

        internal static string Search_Toast_ResetDone {
            get {
                return ResourceManager.GetString("Search_Toast_ResetDone", resourceCulture);
            }
        }

        internal static string Search_Toast_ResultsOnMain {
            get {
                return ResourceManager.GetString("Search_Toast_ResultsOnMain", resourceCulture);
            }
        }

        internal static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }

        internal static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }

        internal static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }

        internal static string UploadButtonLabel {
            get {
                return ResourceManager.GetString("UploadButtonLabel", resourceCulture);
            }
        }

        internal static string UploadLanguageLabel {
            get {
                return ResourceManager.GetString("UploadLanguageLabel", resourceCulture);
            }
        }

        internal static string UploadTitle {
            get {
                return ResourceManager.GetString("UploadTitle", resourceCulture);
            }
        }

        internal static string TranslationTitle {
            get {
                return ResourceManager.GetString("TranslationTitle", resourceCulture);
            }
        }

        internal static string TranslationTargetLanguageLabel {
            get {
                return ResourceManager.GetString("TranslationTargetLanguageLabel", resourceCulture);
            }
        }

        internal static string TranslationButtonLabel {
            get {
                return ResourceManager.GetString("TranslationButtonLabel", resourceCulture);
            }
        }

        internal static string TranslationCancelButtonLabel {
            get {
                return ResourceManager.GetString("TranslationCancelButtonLabel", resourceCulture);
            }
        }

        internal static string AfterTranslationHint {
            get {
                return ResourceManager.GetString("AfterTranslationHint", resourceCulture);
            }
        }

        internal static string TranslationNotImplementedHint {
            get {
                return ResourceManager.GetString("TranslationNotImplementedHint", resourceCulture);
            }
        }

        internal static string TranslationActiveJobRunningMessage {
            get {
                return ResourceManager.GetString("TranslationActiveJobRunningMessage", resourceCulture);
            }
        }

        internal static string TranslationBookPollNetworkNote {
            get {
                return ResourceManager.GetString("TranslationBookPollNetworkNote", resourceCulture);
            }
        }

        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }

        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }

        internal static string Common_Wait {
            get {
                return ResourceManager.GetString("Common_Wait", resourceCulture);
            }
        }

        internal static string Alert_BookNotFound {
            get {
                return ResourceManager.GetString("Alert_BookNotFound", resourceCulture);
            }
        }

        internal static string Alert_LocalBookFileMissing {
            get {
                return ResourceManager.GetString("Alert_LocalBookFileMissing", resourceCulture);
            }
        }

        internal static string Alert_OpenBookFailed {
            get {
                return ResourceManager.GetString("Alert_OpenBookFailed", resourceCulture);
            }
        }

        internal static string Alert_LastBookMissing {
            get {
                return ResourceManager.GetString("Alert_LastBookMissing", resourceCulture);
            }
        }

        internal static string Reading_WaitPages {
            get {
                return ResourceManager.GetString("Reading_WaitPages", resourceCulture);
            }
        }

        internal static string Reading_InvalidPageNumberInput {
            get {
                return ResourceManager.GetString("Reading_InvalidPageNumberInput", resourceCulture);
            }
        }

        internal static string Reading_TocUnavailable {
            get {
                return ResourceManager.GetString("Reading_TocUnavailable", resourceCulture);
            }
        }

        internal static string Reading_NotesComingSoon {
            get {
                return ResourceManager.GetString("Reading_NotesComingSoon", resourceCulture);
            }
        }

        internal static string Reading_JumpPageTitle {
            get {
                return ResourceManager.GetString("Reading_JumpPageTitle", resourceCulture);
            }
        }

        internal static string Reading_JumpPagePrompt {
            get {
                return ResourceManager.GetString("Reading_JumpPagePrompt", resourceCulture);
            }
        }

        internal static string Reading_JumpPageConfirm {
            get {
                return ResourceManager.GetString("Reading_JumpPageConfirm", resourceCulture);
            }
        }

        internal static string Reading_Chrome_Back {
            get {
                return ResourceManager.GetString("Reading_Chrome_Back", resourceCulture);
            }
        }

        internal static string Reading_Chrome_Toc {
            get {
                return ResourceManager.GetString("Reading_Chrome_Toc", resourceCulture);
            }
        }

        internal static string Reading_Chrome_Notes {
            get {
                return ResourceManager.GetString("Reading_Chrome_Notes", resourceCulture);
            }
        }

        internal static string Reading_Chrome_Home {
            get {
                return ResourceManager.GetString("Reading_Chrome_Home", resourceCulture);
            }
        }

        internal static string Reading_Chrome_TextSettings {
            get {
                return ResourceManager.GetString("Reading_Chrome_TextSettings", resourceCulture);
            }
        }

        internal static string Reading_Chrome_AppSettings {
            get {
                return ResourceManager.GetString("Reading_Chrome_AppSettings", resourceCulture);
            }
        }

        internal static string Reading_TocTitle {
            get {
                return ResourceManager.GetString("Reading_TocTitle", resourceCulture);
            }
        }

        internal static string Reading_OpeningBook {
            get {
                return ResourceManager.GetString("Reading_OpeningBook", resourceCulture);
            }
        }

        internal static string Reading_OpeningNotePosition {
            get {
                return ResourceManager.GetString("Reading_OpeningNotePosition", resourceCulture);
            }
        }

        internal static string Reading_ApplyingTextSettings {
            get {
                return ResourceManager.GetString("Reading_ApplyingTextSettings", resourceCulture);
            }
        }

        internal static string Reading_PageProgressFormat {
            get {
                return ResourceManager.GetString("Reading_PageProgressFormat", resourceCulture);
            }
        }

        internal static string Reading_ChapterNumberFormat {
            get {
                return ResourceManager.GetString("Reading_ChapterNumberFormat", resourceCulture);
            }
        }

        internal static string Reading_Title {
            get {
                return ResourceManager.GetString("Reading_Title", resourceCulture);
            }
        }

        internal static string Search_Reset {
            get {
                return ResourceManager.GetString("Search_Reset", resourceCulture);
            }
        }

        internal static string Search_Filter_Title {
            get {
                return ResourceManager.GetString("Search_Filter_Title", resourceCulture);
            }
        }

        internal static string Search_Filter_Author {
            get {
                return ResourceManager.GetString("Search_Filter_Author", resourceCulture);
            }
        }

        internal static string Search_Placeholder_Title {
            get {
                return ResourceManager.GetString("Search_Placeholder_Title", resourceCulture);
            }
        }

        internal static string Search_Placeholder_Author {
            get {
                return ResourceManager.GetString("Search_Placeholder_Author", resourceCulture);
            }
        }

        internal static string Search_Filter_BookSize {
            get {
                return ResourceManager.GetString("Search_Filter_BookSize", resourceCulture);
            }
        }

        internal static string Search_Placeholder_PageFrom {
            get {
                return ResourceManager.GetString("Search_Placeholder_PageFrom", resourceCulture);
            }
        }

        internal static string Search_Placeholder_PageTo {
            get {
                return ResourceManager.GetString("Search_Placeholder_PageTo", resourceCulture);
            }
        }

        internal static string Search_Filter_Status {
            get {
                return ResourceManager.GetString("Search_Filter_Status", resourceCulture);
            }
        }

        internal static string Search_Filter_Reaction {
            get {
                return ResourceManager.GetString("Search_Filter_Reaction", resourceCulture);
            }
        }

        internal static string Search_Filter_Sort {
            get {
                return ResourceManager.GetString("Search_Filter_Sort", resourceCulture);
            }
        }

        internal static string Search_ApplyResults {
            get {
                return ResourceManager.GetString("Search_ApplyResults", resourceCulture);
            }
        }

        internal static string Picker_SelectStatus {
            get {
                return ResourceManager.GetString("Picker_SelectStatus", resourceCulture);
            }
        }

        internal static string Picker_SelectReaction {
            get {
                return ResourceManager.GetString("Picker_SelectReaction", resourceCulture);
            }
        }

        internal static string Picker_SelectSort {
            get {
                return ResourceManager.GetString("Picker_SelectSort", resourceCulture);
            }
        }

        internal static string Search_Page_Header {
            get {
                return ResourceManager.GetString("Search_Page_Header", resourceCulture);
            }
        }

        internal static string Search_Back {
            get {
                return ResourceManager.GetString("Search_Back", resourceCulture);
            }
        }

        internal static string Search_Reset_Button {
            get {
                return ResourceManager.GetString("Search_Reset_Button", resourceCulture);
            }
        }

        internal static string Search_Show_Button {
            get {
                return ResourceManager.GetString("Search_Show_Button", resourceCulture);
            }
        }

        internal static string Search_Toast_Empty {
            get {
                return ResourceManager.GetString("Search_Toast_Empty", resourceCulture);
            }
        }

        internal static string Search_Toast_InvalidPages {
            get {
                return ResourceManager.GetString("Search_Toast_InvalidPages", resourceCulture);
            }
        }

        internal static string Search_Validation_PagePositive {
            get {
                return ResourceManager.GetString("Search_Validation_PagePositive", resourceCulture);
            }
        }

        internal static string Search_Validation_PageToLessThanFrom {
            get {
                return ResourceManager.GetString("Search_Validation_PageToLessThanFrom", resourceCulture);
            }
        }

        internal static string Note_BackTooltip {
            get {
                return ResourceManager.GetString("Note_BackTooltip", resourceCulture);
            }
        }

        internal static string Note_PageTitle {
            get {
                return ResourceManager.GetString("Note_PageTitle", resourceCulture);
            }
        }

        internal static string Note_AddComingSoonTitle {
            get {
                return ResourceManager.GetString("Note_AddComingSoonTitle", resourceCulture);
            }
        }

        internal static string Note_AddComingSoonBody {
            get {
                return ResourceManager.GetString("Note_AddComingSoonBody", resourceCulture);
            }
        }

        internal static string Note_MyNotes {
            get {
                return ResourceManager.GetString("Note_MyNotes", resourceCulture);
            }
        }

        internal static string Note_AddNote {
            get {
                return ResourceManager.GetString("Note_AddNote", resourceCulture);
            }
        }

        internal static string Note_TapHint {
            get {
                return ResourceManager.GetString("Note_TapHint", resourceCulture);
            }
        }

        internal static string Note_CommentHint {
            get {
                return ResourceManager.GetString("Note_CommentHint", resourceCulture);
            }
        }

        internal static string Note_SampleTitle {
            get {
                return ResourceManager.GetString("Note_SampleTitle", resourceCulture);
            }
        }

        internal static string Note_SamplePage {
            get {
                return ResourceManager.GetString("Note_SamplePage", resourceCulture);
            }
        }

        internal static string TextSettings_PageTitle {
            get {
                return ResourceManager.GetString("TextSettings_PageTitle", resourceCulture);
            }
        }

        internal static string TextSettings_FontSize {
            get {
                return ResourceManager.GetString("TextSettings_FontSize", resourceCulture);
            }
        }

        internal static string TextSettings_BgColor {
            get {
                return ResourceManager.GetString("TextSettings_BgColor", resourceCulture);
            }
        }

        internal static string TextSettings_FgColor {
            get {
                return ResourceManager.GetString("TextSettings_FgColor", resourceCulture);
            }
        }

        internal static string TextSettings_PickColor {
            get {
                return ResourceManager.GetString("TextSettings_PickColor", resourceCulture);
            }
        }

        internal static string TextSettings_Margins {
            get {
                return ResourceManager.GetString("TextSettings_Margins", resourceCulture);
            }
        }

        internal static string TextSettings_Alignment {
            get {
                return ResourceManager.GetString("TextSettings_Alignment", resourceCulture);
            }
        }

        internal static string TextSettings_Align_Center {
            get {
                return ResourceManager.GetString("TextSettings_Align_Center", resourceCulture);
            }
        }

        internal static string TextSettings_Align_End {
            get {
                return ResourceManager.GetString("TextSettings_Align_End", resourceCulture);
            }
        }

        internal static string TextSettings_Align_Justify {
            get {
                return ResourceManager.GetString("TextSettings_Align_Justify", resourceCulture);
            }
        }

        internal static string TextSettings_Align_Start {
            get {
                return ResourceManager.GetString("TextSettings_Align_Start", resourceCulture);
            }
        }

        internal static string TextSettings_Picker_Alignment {
            get {
                return ResourceManager.GetString("TextSettings_Picker_Alignment", resourceCulture);
            }
        }

        internal static string TextSettings_Picker_Scrolling {
            get {
                return ResourceManager.GetString("TextSettings_Picker_Scrolling", resourceCulture);
            }
        }

        internal static string TextSettings_Scroll_Horizontal {
            get {
                return ResourceManager.GetString("TextSettings_Scroll_Horizontal", resourceCulture);
            }
        }

        internal static string TextSettings_Scroll_Vertical {
            get {
                return ResourceManager.GetString("TextSettings_Scroll_Vertical", resourceCulture);
            }
        }

        internal static string TextSettings_PageTurn {
            get {
                return ResourceManager.GetString("TextSettings_PageTurn", resourceCulture);
            }
        }

        internal static string TextSettings_TranslatorLang {
            get {
                return ResourceManager.GetString("TextSettings_TranslatorLang", resourceCulture);
            }
        }

        internal static string TextSettings_ColorDialogTitle {
            get {
                return ResourceManager.GetString("TextSettings_ColorDialogTitle", resourceCulture);
            }
        }

        internal static string Theme_Name_Light {
            get {
                return ResourceManager.GetString("Theme_Name_Light", resourceCulture);
            }
        }

        internal static string Theme_Name_Dark {
            get {
                return ResourceManager.GetString("Theme_Name_Dark", resourceCulture);
            }
        }

        internal static string Theme_Name_Auto {
            get {
                return ResourceManager.GetString("Theme_Name_Auto", resourceCulture);
            }
        }

        internal static string Interface_Language_Setting {
            get {
                return ResourceManager.GetString("Interface_Language_Setting", resourceCulture);
            }
        }

        internal static string Interface_Language_Display_Ru {
            get {
                return ResourceManager.GetString("Interface_Language_Display_Ru", resourceCulture);
            }
        }

        internal static string Interface_Language_Display_En {
            get {
                return ResourceManager.GetString("Interface_Language_Display_En", resourceCulture);
            }
        }

        internal static string Interface_Language_Title {
            get {
                return ResourceManager.GetString("Interface_Language_Title", resourceCulture);
            }
        }

        internal static string Interface_FontSize_Small {
            get {
                return ResourceManager.GetString("Interface_FontSize_Small", resourceCulture);
            }
        }

        internal static string Interface_FontSize_Medium {
            get {
                return ResourceManager.GetString("Interface_FontSize_Medium", resourceCulture);
            }
        }

        internal static string Interface_FontSize_Large {
            get {
                return ResourceManager.GetString("Interface_FontSize_Large", resourceCulture);
            }
        }

        internal static string Interface_FontSize_Format {
            get {
                return ResourceManager.GetString("Interface_FontSize_Format", resourceCulture);
            }
        }

        internal static string Notification_InvalidUploadFormat {
            get {
                return ResourceManager.GetString("Notification_InvalidUploadFormat", resourceCulture);
            }
        }

        internal static string Notification_UploadCancelled {
            get {
                return ResourceManager.GetString("Notification_UploadCancelled", resourceCulture);
            }
        }

        internal static string Notification_UploadFailedGeneric {
            get {
                return ResourceManager.GetString("Notification_UploadFailedGeneric", resourceCulture);
            }
        }

        internal static string Notification_UploadFailedGenericLater {
            get {
                return ResourceManager.GetString("Notification_UploadFailedGenericLater", resourceCulture);
            }
        }

        internal static string Notification_UploadFailedWithDetail {
            get {
                return ResourceManager.GetString("Notification_UploadFailedWithDetail", resourceCulture);
            }
        }

        internal static string Notification_UploadSuccessTapOpen {
            get {
                return ResourceManager.GetString("Notification_UploadSuccessTapOpen", resourceCulture);
            }
        }

        internal static string Notification_TranslationExpired {
            get {
                return ResourceManager.GetString("Notification_TranslationExpired", resourceCulture);
            }
        }

        internal static string Notification_TranslationCompleteFormat {
            get {
                return ResourceManager.GetString("Notification_TranslationCompleteFormat", resourceCulture);
            }
        }

        internal static string Notification_Upload_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Notification_Upload_ServiceUnavailable", resourceCulture);
            }
        }

        internal static string Notification_Upload_TimeoutTwoMinutes {
            get {
                return ResourceManager.GetString("Notification_Upload_TimeoutTwoMinutes", resourceCulture);
            }
        }

        internal static string Notification_Upload_ReadBookFileFailed {
            get {
                return ResourceManager.GetString("Notification_Upload_ReadBookFileFailed", resourceCulture);
            }
        }

        internal static string Notification_Upload_UnexpectedFailure {
            get {
                return ResourceManager.GetString("Notification_Upload_UnexpectedFailure", resourceCulture);
            }
        }

        internal static string Notification_Translation_PollTimeout24Hours {
            get {
                return ResourceManager.GetString("Notification_Translation_PollTimeout24Hours", resourceCulture);
            }
        }

        internal static string Notification_Translation_UserStopped {
            get {
                return ResourceManager.GetString("Notification_Translation_UserStopped", resourceCulture);
            }
        }

        internal static string Notification_Translation_OfflineNoInternet {
            get {
                return ResourceManager.GetString("Notification_Translation_OfflineNoInternet", resourceCulture);
            }
        }

        internal static string Notification_Translation_FailedGeneric {
            get {
                return ResourceManager.GetString("Notification_Translation_FailedGeneric", resourceCulture);
            }
        }

        internal static string A11y_Notification_Close {
            get {
                return ResourceManager.GetString("A11y_Notification_Close", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_Generic {
            get {
                return ResourceManager.GetString("TranslationApi_Error_Generic", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_InvalidRequestEmptyText {
            get {
                return ResourceManager.GetString("TranslationApi_Error_InvalidRequestEmptyText", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_InvalidRequestMultipartExpected {
            get {
                return ResourceManager.GetString("TranslationApi_Error_InvalidRequestMultipartExpected", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_InvalidRequestNoFile {
            get {
                return ResourceManager.GetString("TranslationApi_Error_InvalidRequestNoFile", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_InvalidLanguageMissing {
            get {
                return ResourceManager.GetString("TranslationApi_Error_InvalidLanguageMissing", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_UpstreamError {
            get {
                return ResourceManager.GetString("TranslationApi_Error_UpstreamError", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_InternalError {
            get {
                return ResourceManager.GetString("TranslationApi_Error_InternalError", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_InternalErrorEmptyTranslation {
            get {
                return ResourceManager.GetString("TranslationApi_Error_InternalErrorEmptyTranslation", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_JobNotFound {
            get {
                return ResourceManager.GetString("TranslationApi_Error_JobNotFound", resourceCulture);
            }
        }

        internal static string TranslationApi_Error_ResultExpired {
            get {
                return ResourceManager.GetString("TranslationApi_Error_ResultExpired", resourceCulture);
            }
        }

        internal static string TranslationApi_Start_Rejected {
            get {
                return ResourceManager.GetString("TranslationApi_Start_Rejected", resourceCulture);
            }
        }

        internal static string TranslationApi_Start_FailedGeneric {
            get {
                return ResourceManager.GetString("TranslationApi_Start_FailedGeneric", resourceCulture);
            }
        }

        internal static string TranslationApi_Start_ResponseIncomplete {
            get {
                return ResourceManager.GetString("TranslationApi_Start_ResponseIncomplete", resourceCulture);
            }
        }

        internal static string Translation_Msg_OfflineUnavailable {
            get {
                return ResourceManager.GetString("Translation_Msg_OfflineUnavailable", resourceCulture);
            }
        }

        internal static string Translation_Msg_ProxyUnreachable {
            get {
                return ResourceManager.GetString("Translation_Msg_ProxyUnreachable", resourceCulture);
            }
        }

        internal static string Translation_Msg_OnlineFailure {
            get {
                return ResourceManager.GetString("Translation_Msg_OnlineFailure", resourceCulture);
            }
        }

        internal static string Translation_Msg_CancelledOrTimeout {
            get {
                return ResourceManager.GetString("Translation_Msg_CancelledOrTimeout", resourceCulture);
            }
        }

        internal static string Translation_Msg_ServerNotConfigured {
            get {
                return ResourceManager.GetString("Translation_Msg_ServerNotConfigured", resourceCulture);
            }
        }

        internal static string Main_SearchNoBooksFound {
            get {
                return ResourceManager.GetString("Main_SearchNoBooksFound", resourceCulture);
            }
        }

        internal static string Main_SearchApplied {
            get {
                return ResourceManager.GetString("Main_SearchApplied", resourceCulture);
            }
        }

        internal static string Main_SearchResetDone {
            get {
                return ResourceManager.GetString("Main_SearchResetDone", resourceCulture);
            }
        }

        internal static string Main_BookNotFoundMaybeRemoved {
            get {
                return ResourceManager.GetString("Main_BookNotFoundMaybeRemoved", resourceCulture);
            }
        }

        internal static string Main_LibraryEmptyHint {
            get {
                return ResourceManager.GetString("Main_LibraryEmptyHint", resourceCulture);
            }
        }

        internal static string Main_NoSavedReadingHint {
            get {
                return ResourceManager.GetString("Main_NoSavedReadingHint", resourceCulture);
            }
        }

        internal static string Main_FileMissingForSavedPosition {
            get {
                return ResourceManager.GetString("Main_FileMissingForSavedPosition", resourceCulture);
            }
        }

        internal static string Main_DeleteBlockedTranslationRunning {
            get {
                return ResourceManager.GetString("Main_DeleteBlockedTranslationRunning", resourceCulture);
            }
        }

        internal static string Main_DeleteFailed {
            get {
                return ResourceManager.GetString("Main_DeleteFailed", resourceCulture);
            }
        }

        internal static string Main_CardDeletedSuccess {
            get {
                return ResourceManager.GetString("Main_CardDeletedSuccess", resourceCulture);
            }
        }

        internal static string Card_ContextMenuTitle {
            get {
                return ResourceManager.GetString("Card_ContextMenuTitle", resourceCulture);
            }
        }

        internal static string Card_Action_Delete {
            get {
                return ResourceManager.GetString("Card_Action_Delete", resourceCulture);
            }
        }

        internal static string Card_Action_Translate {
            get {
                return ResourceManager.GetString("Card_Action_Translate", resourceCulture);
            }
        }

        internal static string Card_Action_ReadMark {
            get {
                return ResourceManager.GetString("Card_Action_ReadMark", resourceCulture);
            }
        }

        internal static string Card_Action_ReadUnmark {
            get {
                return ResourceManager.GetString("Card_Action_ReadUnmark", resourceCulture);
            }
        }

        internal static string Card_Action_FavMark {
            get {
                return ResourceManager.GetString("Card_Action_FavMark", resourceCulture);
            }
        }

        internal static string Card_Action_FavUnmark {
            get {
                return ResourceManager.GetString("Card_Action_FavUnmark", resourceCulture);
            }
        }

        internal static string Card_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("Card_DeleteConfirmTitle", resourceCulture);
            }
        }

        internal static string Card_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("Card_DeleteConfirmMessage", resourceCulture);
            }
        }

        internal static string Card_DeleteConfirmYes {
            get {
                return ResourceManager.GetString("Card_DeleteConfirmYes", resourceCulture);
            }
        }

        internal static string Book_NoTitle {
            get {
                return ResourceManager.GetString("Book_NoTitle", resourceCulture);
            }
        }

        internal static string Book_UnknownAuthor {
            get {
                return ResourceManager.GetString("Book_UnknownAuthor", resourceCulture);
            }
        }

        internal static string Reading_Error_LoadBookText {
            get {
                return ResourceManager.GetString("Reading_Error_LoadBookText", resourceCulture);
            }
        }

        internal static string Reading_Error_OpenBookDetail {
            get {
                return ResourceManager.GetString("Reading_Error_OpenBookDetail", resourceCulture);
            }
        }

        internal static string Reading_EndOfBook {
            get {
                return ResourceManager.GetString("Reading_EndOfBook", resourceCulture);
            }
        }

        internal static string Reading_Fallback_Fb2ZipMissing {
            get {
                return ResourceManager.GetString("Reading_Fallback_Fb2ZipMissing", resourceCulture);
            }
        }

        internal static string Reading_Fallback_UnsupportedFormat {
            get {
                return ResourceManager.GetString("Reading_Fallback_UnsupportedFormat", resourceCulture);
            }
        }

        internal static string Reading_Fallback_LoadTextFailed {
            get {
                return ResourceManager.GetString("Reading_Fallback_LoadTextFailed", resourceCulture);
            }
        }

        internal static string Reading_GotoPage_ErrorBelowMinFormat {
            get {
                return ResourceManager.GetString("Reading_GotoPage_ErrorBelowMinFormat", resourceCulture);
            }
        }

        internal static string Reading_GotoPage_ErrorNoSuchPageFormat {
            get {
                return ResourceManager.GetString("Reading_GotoPage_ErrorNoSuchPageFormat", resourceCulture);
            }
        }

        internal static string Reading_TocFallbackBodyTitle {
            get {
                return ResourceManager.GetString("Reading_TocFallbackBodyTitle", resourceCulture);
            }
        }

        internal static string Reading_Error_ReadEpub {
            get {
                return ResourceManager.GetString("Reading_Error_ReadEpub", resourceCulture);
            }
        }

        internal static string Upload_Error_CopyFile {
            get {
                return ResourceManager.GetString("Upload_Error_CopyFile", resourceCulture);
            }
        }

        internal static string Upload_Error_TranslationFileNotFound {
            get {
                return ResourceManager.GetString("Upload_Error_TranslationFileNotFound", resourceCulture);
            }
        }

        internal static string Upload_Error_TargetBookNotFound {
            get {
                return ResourceManager.GetString("Upload_Error_TargetBookNotFound", resourceCulture);
            }
        }

        internal static string Upload_Error_SaveFile {
            get {
                return ResourceManager.GetString("Upload_Error_SaveFile", resourceCulture);
            }
        }

        internal static string Fb2_Error_XmlParseFailed {
            get {
                return ResourceManager.GetString("Fb2_Error_XmlParseFailed", resourceCulture);
            }
        }

        internal static string Fb2_Error_NoBookText {
            get {
                return ResourceManager.GetString("Fb2_Error_NoBookText", resourceCulture);
            }
        }

    }
}
